#cloud-config
# vim:syntax=yaml

growpart:
  mode: auto
  devices: ['/']

{{- if .UpgradePackages }}
package_update: true
package_upgrade: true
package_reboot_if_required: true
{{- end }}

{{- if or (eq .MountType "9p") (eq .MountType "virtiofs") }}
{{- if .Mounts }}
# mounts are not included here
{{- end }}
{{- end }}

{{- if .TimeZone }}
timezone: {{.TimeZone}}
{{- end }}

users:
  - name: "{{.User}}"
    uid: "{{.UID}}"
    homedir: "{{.Home}}"
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: true
    ssh-authorized-keys:
    {{- range $val := .SSHPubKeys }}
      - {{ printf "%q" $val }}
    {{- end }}

{{- if .DNSAddresses }}
# resolv_conf is not included here
{{- end }}

{{ with .CACerts }}
ca_certs:
  remove_defaults: {{ .RemoveDefaults }}
  {{- if .Trusted}}
  trusted:
  {{- range $cert := .Trusted }}
  - |
    {{- range $line := $cert.Lines }}
    {{ $line }}
    {{- end }}
  {{- end }}
  {{- end }}
{{- end }}

{{- if .BootCmds }}
bootcmd:
  {{- range $cmd := $.BootCmds }}
- |
    {{- range $line := $cmd.Lines }}
  {{ $line }}
    {{- end }}
  {{- end }}
{{- end }}
